[package]
name = "bump-rs"
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "collision detection library based on bump.lua"
repository = "https://github.com/BitSkyStudio/bump-rs"
keywords = ["collision"]

[dependencies]
nalgebra = "0.33"
generational-arena = "0.2"